# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish
      run: dotnet publish --configuration Release
  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Create release ZIP
        shell: pwsh
        working-directory: ${{ github.workspace }}/DiscordConverter.App/bin/Release/net8.0-windows
        run: Compress-Archive -Path ./publish/* -DestinationPath DiscordConverter.zip -CompressionLevel Fastest
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/DiscordConverter.App/bin/Release/net8.0-windows/DiscordConverter.zip
      
